# 应用服务 WEB 访问端口
server:
  port: 8080

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/bingli?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2B8
  main:
    allow-circular-references: true





#mappper映射地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity

#分页插件配置
pagehelper:
  #dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
